CREATE DATABASE IF NOT EXISTS `employeeportal`;
USE `employeeportal`;


CREATE TABLE IF NOT EXISTS tbluser (
  id INT(11) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  email VARCHAR(255) NOT NULL,
  password VARCHAR(255) NOT NULL,
  firstName VARCHAR(255) NOT NULL,
  lastName VARCHAR(255) NOT NULL,
  address VARCHAR(255) NOT NULL,
  phone VARCHAR(255) NOT NULL,
  salary DECIMAL(10,2) NOT NULL,
  SSN VARCHAR(255) NOT NULL
);